/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBTOSLLMODEL
#define ROOBTOSLLMODEL

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBtosllModel : public RooAbsPdf {
public:
  RooBtosllModel() {} ; 
  RooBtosllModel(const char *name, const char *title,
	      RooAbsReal& _CosThetaL,
	      RooAbsReal& _CosThetaK,
	      RooAbsReal& _unboundAfb,
	      RooAbsReal& _unboundFl,
	      RooAbsReal& _fs,
	      RooAbsReal& _transAs);
  RooBtosllModel(const RooBtosllModel& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBtosllModel(*this,newname); }
  inline virtual ~RooBtosllModel() { }

protected:

  RooRealProxy CosThetaL ;
  RooRealProxy CosThetaK ;
  RooRealProxy unboundAfb ;
  RooRealProxy unboundFl ;
  RooRealProxy fs ;
  RooRealProxy transAs ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBtosllModel,1) // Your description goes here...
};
 
#endif
